# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            #gem update --system
            gem install bundler

      - run:
          name: Install Gems
          command: |
            bundle install

      - run:
          name: Build Site
          command: |
            bundle exec jekyll build

      - run:
          name: Run htmlproofer
          command: |
            bundle exec htmlproofer ./_site

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
